### ISSUE TITLE
Crash on plugin install

### ISSUE THREAD

**Issue by markjessell** [ThreePointPlugin/ThreePointMethod#2]
Hi, 

looks like a great idea for a plugin, but using version 3.32.0-Lima of QGIS I get this error on installation:

Couldn't load plugin 'ThreePointMethod' due to an error when calling its classFactory() method 

TypeError: 'QVariant' object is not subscriptable 
Traceback (most recent call last):
  File "C:\PROGRA~1/QGIS33~1.0/apps/qgis/./python\qgis\utils.py", line 423, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:\Users/00073294/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\ThreePointMethod\__init__.py", line 36, in classFactory
    return ThreePointMethod(iface)
  File "C:\Users/00073294/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\ThreePointMethod\ThreePointMethod.py", line 59, in __init__
    locale = QSettings().value('locale/userLocale')[0:2]
TypeError: 'QVariant' object is not subscriptable

Python version: 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] 
QGIS version: 3.32.0-Lima Lima, 311a8cb8a6 

Python Path:
C:\Users/00073294/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\OpenTopography-DEM-Downloader
C:/PROGRA~1/QGIS33~1.0/apps/qgis/./python
C:/Users/00073294/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/00073294/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/PROGRA~1/QGIS33~1.0/apps/qgis/./python/plugins
C:\PROGRA~1\QGIS33~1.0\apps\grass\grass82\etc\python
C:\Users\00073294\Documents
C:\Program Files\QGIS 3.32.0\bin\python39.zip
C:\PROGRA~1\QGIS33~1.0\apps\Python39\DLLs
C:\PROGRA~1\QGIS33~1.0\apps\Python39\lib
C:\Program Files\QGIS 3.32.0\bin
C:\Users\00073294\AppData\Roaming\Python\Python39\site-packages
C:\PROGRA~1\QGIS33~1.0\apps\Python39
C:\PROGRA~1\QGIS33~1.0\apps\Python39\lib\site-packages
C:\PROGRA~1\QGIS33~1.0\apps\Python39\lib\site-packages\win32
C:\PROGRA~1\QGIS33~1.0\apps\Python39\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS33~1.0\apps\Python39\lib\site-packages\Pythonwin
C:/Users/00073294/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:\Users\00073294\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\mmqgis/forms
C:\Users\00073294\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\openlog\embedded_external_libs
.
C:/Users/00073294/Dropbox/cet_courses/python_for_explorers/Data for Python course/mwj/maps

**Comment by ewwbrach** [comment]
Hi, please try deleting folder with the plugin. I found the similiar problem, and the most popular solutions that turned out to be effective is uninstalling and reinstalling the plugin, or restarting QGIS. It is a link to a similar problem and solution https://github.com/linz/linz-data-importer/issues/146#issue-934145907

**Comment by markjessell** [comment]
Hi

Thanks for the tip, I modified the following two lines in ThreePointMethod.py:

24 from qgis.PyQt.QtCore import  QTranslator, QCoreApplication

59 locale = QgsSettings().value('locale/userLocale')[0:2]

And all is good, neat plugin!

Cheers

Mark
